### PR TITLE
De-namespace

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

Remove namespace package following the formalism in https://github.com/sot/ska_sun/pull/22.

## Interface impacts

None

### Unit tests

- [x] Mac (local `test.py` within git repo)

### Functional tests

- Installed and confirmed expected packages / functions / versions
- Built docs and confirmed they look reasonable (fixed a latent problem in docs)

### CODE REVIEW

**Comment by javierggt** [comment]
There are too many command-related libraries for my taste 😄 

I just note that the new name is `parsecm` while up to now in other modules you have always used `parse_cm`. In the camel-case one could see the structure, but not anymore.

**Comment by taldcroft** [comment]
@javierggt - this package is scheduled for removal this year, having been replaced by `parse_cm`. After ska3-prime I'll put an exception into the import with an env-var override. This way we will flush out any hidden dependencies and then finally remove this from ska3.

**Comment by taldcroft** [comment]
This still needs approval.

**Review by javierggt — APPROVED** [review]
Looks good to me. I also built the docs and ran the test.

**Pull request merged**
